export function Footer() {
  return (
    <footer className="border-t border-japandi-sand/50 bg-japandi-charcoal px-6 py-12 text-center md:px-10">
      <p className="font-serif text-lg font-semibold text-japandi-warm-white">
        State of World Models in 2026
      </p>
      <p className="mt-2 text-sm leading-relaxed text-japandi-sand/60">
        The February 2026 inflection point is here. The tools, communities, and opportunities are
        accessible. Your journey into world models begins with a single step into one of these entry
        pathways.
      </p>
      <div className="mt-8 h-px w-12 mx-auto bg-japandi-sand/20" />
      <p className="mt-6 font-mono text-[10px] uppercase tracking-[0.2em] text-japandi-mist/40">
        Generated by Superagent.
      </p>
    </footer>
  );
}
